/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.emeresys.emeresysfrontend;
import java.awt.CardLayout;
import com.emeresys.emeresysfrontend.MapViewerUtils;
import org.openstreetmap.gui.jmapviewer.*;
import com.emeresys.emeresysfrontend.NewsTicker;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author USER
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setupMapView();
        setupAlertsPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePane = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        commButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();
        viewpanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        SummaryCards = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        alertsPanel = new javax.swing.JPanel();
        mapView = new javax.swing.JPanel();
        communications = new javax.swing.JPanel();
        statistics = new javax.swing.JPanel();
        chartSelectorPanel = new javax.swing.JPanel();
        btnUsers = new javax.swing.JButton();
        btnResponders = new javax.swing.JButton();
        btnResources = new javax.swing.JButton();
        chartDisplayPanel = new javax.swing.JPanel();
        usersPanel = new javax.swing.JPanel();
        respondersPanel = new javax.swing.JPanel();
        resourcesPanel = new javax.swing.JPanel();
        options = new javax.swing.JPanel();
        settingsTopNav = new javax.swing.JPanel();
        accountSettings = new javax.swing.JButton();
        displaySettings = new javax.swing.JButton();
        about = new javax.swing.JButton();
        settingsView = new javax.swing.JPanel();
        accountPanel = new javax.swing.JPanel();
        displayPanel = new javax.swing.JPanel();
        aboutPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMERESYS ADMIN");

        SidePane.setBackground(new java.awt.Color(255, 255, 204));
        SidePane.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        SidePane.setMinimumSize(new java.awt.Dimension(75, 100));
        SidePane.setPreferredSize(new java.awt.Dimension(100, 600));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        SidePane.setLayout(flowLayout1);

        dashboardButton.setBackground(new java.awt.Color(204, 255, 204));
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        dashboardButton.setPreferredSize(new java.awt.Dimension(100, 100));
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });
        SidePane.add(dashboardButton);

        commButton.setBackground(new java.awt.Color(204, 255, 255));
        commButton.setText("Comm");
        commButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        commButton.setPreferredSize(new java.awt.Dimension(100, 100));
        commButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commButtonActionPerformed(evt);
            }
        });
        SidePane.add(commButton);

        statsButton.setBackground(new java.awt.Color(204, 204, 255));
        statsButton.setText("Stats");
        statsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        statsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        statsButton.setPreferredSize(new java.awt.Dimension(100, 100));
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });
        SidePane.add(statsButton);

        optionsButton.setBackground(new java.awt.Color(255, 204, 204));
        optionsButton.setText("Options");
        optionsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        optionsButton.setPreferredSize(new java.awt.Dimension(100, 100));
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonActionPerformed(evt);
            }
        });
        SidePane.add(optionsButton);

        getContentPane().add(SidePane, java.awt.BorderLayout.LINE_START);

        viewpanel.setBackground(new java.awt.Color(255, 255, 255));
        viewpanel.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(204, 255, 204));
        dashboard.setLayout(new java.awt.BorderLayout());

        SummaryCards.setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.background"));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 100));

        jLabel1.setText("<html><b>Active<b><br>Disasters: </html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        SummaryCards.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 100));

        jLabel2.setText("<html><b>Responders<b><br>Active: </html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        SummaryCards.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 100));

        jLabel3.setText("<html><b>Resources<b><br>Used: </html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        SummaryCards.add(jPanel3);

        dashboard.add(SummaryCards, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout alertsPanelLayout = new javax.swing.GroupLayout(alertsPanel);
        alertsPanel.setLayout(alertsPanelLayout);
        alertsPanelLayout.setHorizontalGroup(
            alertsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        alertsPanelLayout.setVerticalGroup(
            alertsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        dashboard.add(alertsPanel, java.awt.BorderLayout.PAGE_END);

        mapView.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout mapViewLayout = new javax.swing.GroupLayout(mapView);
        mapView.setLayout(mapViewLayout);
        mapViewLayout.setHorizontalGroup(
            mapViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        mapViewLayout.setVerticalGroup(
            mapViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        dashboard.add(mapView, java.awt.BorderLayout.CENTER);

        viewpanel.add(dashboard, "dashboard");

        communications.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout communicationsLayout = new javax.swing.GroupLayout(communications);
        communications.setLayout(communicationsLayout);
        communicationsLayout.setHorizontalGroup(
            communicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        communicationsLayout.setVerticalGroup(
            communicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );

        viewpanel.add(communications, "communications");

        statistics.setBackground(new java.awt.Color(204, 204, 255));
        statistics.setLayout(new java.awt.BorderLayout());

        chartSelectorPanel.setPreferredSize(new java.awt.Dimension(700, 50));

        btnUsers.setBackground(new java.awt.Color(255, 204, 204));
        btnUsers.setText("Users");
        btnUsers.setPreferredSize(new java.awt.Dimension(100, 50));
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        chartSelectorPanel.add(btnUsers);

        btnResponders.setBackground(new java.awt.Color(204, 255, 204));
        btnResponders.setText("Responders");
        btnResponders.setPreferredSize(new java.awt.Dimension(100, 50));
        btnResponders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespondersActionPerformed(evt);
            }
        });
        chartSelectorPanel.add(btnResponders);

        btnResources.setBackground(new java.awt.Color(255, 255, 204));
        btnResources.setText("Resources");
        btnResources.setPreferredSize(new java.awt.Dimension(100, 50));
        btnResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResourcesActionPerformed(evt);
            }
        });
        chartSelectorPanel.add(btnResources);

        statistics.add(chartSelectorPanel, java.awt.BorderLayout.PAGE_START);

        chartDisplayPanel.setBackground(new java.awt.Color(204, 204, 255));
        chartDisplayPanel.setLayout(new java.awt.CardLayout());

        usersPanel.setBackground(new java.awt.Color(255, 204, 255));
        usersPanel.setLayout(new javax.swing.BoxLayout(usersPanel, javax.swing.BoxLayout.LINE_AXIS));
        chartDisplayPanel.add(usersPanel, "usersPanel");

        respondersPanel.setBackground(new java.awt.Color(204, 255, 204));
        respondersPanel.setLayout(new javax.swing.BoxLayout(respondersPanel, javax.swing.BoxLayout.LINE_AXIS));
        chartDisplayPanel.add(respondersPanel, "respondersPanel");

        resourcesPanel.setBackground(new java.awt.Color(255, 255, 204));
        resourcesPanel.setLayout(new javax.swing.BoxLayout(resourcesPanel, javax.swing.BoxLayout.LINE_AXIS));
        chartDisplayPanel.add(resourcesPanel, "resourcesPanel");

        statistics.add(chartDisplayPanel, java.awt.BorderLayout.CENTER);

        viewpanel.add(statistics, "statistics");

        options.setBackground(new java.awt.Color(255, 204, 204));
        options.setLayout(new java.awt.BorderLayout());

        settingsTopNav.setMinimumSize(new java.awt.Dimension(100, 50));
        settingsTopNav.setPreferredSize(new java.awt.Dimension(700, 50));

        accountSettings.setBackground(new java.awt.Color(204, 204, 255));
        accountSettings.setText("Account");
        accountSettings.setPreferredSize(new java.awt.Dimension(100, 50));
        settingsTopNav.add(accountSettings);

        displaySettings.setBackground(new java.awt.Color(204, 255, 204));
        displaySettings.setText("Display");
        displaySettings.setPreferredSize(new java.awt.Dimension(100, 50));
        settingsTopNav.add(displaySettings);

        about.setText("About");
        about.setPreferredSize(new java.awt.Dimension(100, 50));
        settingsTopNav.add(about);

        options.add(settingsTopNav, java.awt.BorderLayout.PAGE_START);

        settingsView.setBackground(new java.awt.Color(255, 51, 51));
        settingsView.setLayout(new java.awt.CardLayout());

        accountPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        settingsView.add(accountPanel, "card2");

        displayPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        settingsView.add(displayPanel, "card3");

        aboutPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        settingsView.add(aboutPanel, "card4");

        options.add(settingsView, java.awt.BorderLayout.CENTER);

        viewpanel.add(options, "options");

        getContentPane().add(viewpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setupAlertsPanel(){
        // create the news ticker instance
        NewsTicker ticker = new NewsTicker();
        alertsPanel.setLayout(new java.awt.BorderLayout());
        alertsPanel.add(ticker, java.awt.BorderLayout.CENTER);
        alertsPanel.revalidate();
        alertsPanel.repaint();
        
    }
    
    
    
    //MapView method
    public void setupMapView(){
        JMapViewer mapViewer = MapViewerUtils.initializeMapViewer(12);
        
        
        mapView.setLayout(new java.awt.BorderLayout());
        mapView.add(mapViewer, java.awt.BorderLayout.CENTER);
        
        mapView.revalidate();
        mapView.repaint();
    }
    
    
    
    
    
    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) viewpanel.getLayout();
        cl.show(viewpanel, "dashboard");
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void commButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) viewpanel.getLayout();
        cl.show(viewpanel, "communications");
    }//GEN-LAST:event_commButtonActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) viewpanel.getLayout();
        cl.show(viewpanel, "statistics");
                
    }//GEN-LAST:event_statsButtonActionPerformed

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) viewpanel.getLayout();
        cl.show(viewpanel, "options");
    }//GEN-LAST:event_optionsButtonActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) chartDisplayPanel.getLayout();
        cl.show(chartDisplayPanel, "usersPanel");
        
        
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnRespondersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespondersActionPerformed
        // TODO add your handling code here:
           CardLayout cl = (CardLayout) chartDisplayPanel.getLayout();
            cl.show(chartDisplayPanel, "respondersPanel");
    }//GEN-LAST:event_btnRespondersActionPerformed

    private void btnResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResourcesActionPerformed
        // TODO add your handling code here:
           CardLayout cl = (CardLayout) chartDisplayPanel.getLayout();
            cl.show(chartDisplayPanel, "resourcesPanel");
    }//GEN-LAST:event_btnResourcesActionPerformed

    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidePane;
    private javax.swing.JPanel SummaryCards;
    private javax.swing.JButton about;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JButton accountSettings;
    private javax.swing.JPanel alertsPanel;
    private javax.swing.JButton btnResources;
    private javax.swing.JButton btnResponders;
    private javax.swing.JButton btnUsers;
    private javax.swing.JPanel chartDisplayPanel;
    private javax.swing.JPanel chartSelectorPanel;
    private javax.swing.JButton commButton;
    private javax.swing.JPanel communications;
    private javax.swing.JPanel dashboard;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton displaySettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mapView;
    private javax.swing.JPanel options;
    private javax.swing.JButton optionsButton;
    private javax.swing.JPanel resourcesPanel;
    private javax.swing.JPanel respondersPanel;
    private javax.swing.JPanel settingsTopNav;
    private javax.swing.JPanel settingsView;
    private javax.swing.JPanel statistics;
    private javax.swing.JButton statsButton;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JPanel viewpanel;
    // End of variables declaration//GEN-END:variables
}
